version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
      
  train:
    build: .
    command: ["python", "train.py"]
    depends_on:
      - rabbitmq
    # Không cần mở cổng cho dịch vụ train

  flask:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - train  # Đảm bảo train hoàn tất trước khi chạy flask
